CMakeLists.txt, Testbed/CMakeLists.txt
This PR:
- solves issue #29,
- resolves another linker error in the Testbed on MSVC from the CMake generated project, and 
- sets the PlayRho default configurations for multi-configuration projects to `Debug` and `Release` only.
- Building using VS 2017 from CMake is improved.
- The last commit specifying default build configurations will also affect XCode projects. I am unable to test this on XCode, but I don't believe it will have a negative impact.
- These changes do not resolve issue #16
Look through commits
Generate project with CMake for VS. Build the Testbed.
This pr moves towards the goal of build automation on major platforms.
#29
=> CMake Build fixes for CMake-generated MSVC projects.

Testbed/CMakeLists.txt
Fixes issue #16.
When `glfw` has been installed using `vcpkg` this correctly includes and links `glfw`. Will behave in the original way when the `find_package` method fails.
Generate build using CMake and build the project.
=> Fix for issue #16

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Common/FlagGuard.hpp, PlayRho/Dynamics/World.cpp, UnitTests/FlagGuard.cpp
Moves `FlagGuard` out from World.cpp and up to general usability. Add associated unit test code. Also removes some stuff no longer used.
Potential reuse now of the `FlagGuard` type. Reduces the size of the `World.cpp` file. Adds to the unit test code coverage amount.
For issue #66.
=> For issue 66

PlayRho/Collision/Manifold.cpp, PlayRho/Common/ArrayList.hpp, PlayRho/Common/Settings.hpp, PlayRho/Defines.hpp, PlayRho/Dynamics/Joints/Joint.cpp
Avoids polluting user code with PlayRho macros (other than header include guards).
Live up to documentation in terms of avoiding name space pollution. Risk should be minimal.
Issue #70.
=> For issue #70.

Benchmark/BenchmarkMain.cpp
Adds trivial benchmarks of detecting differing signs via std::signbit vs. multiplication. I'm seeing that `std::signbit` is slightly faster by virtue of more runs getting done than with alt method.
Isolated to running the Benchmark application.
Related to issue #76 .
=> For issue #76.

Documentation/Doxyfile, PlayRho/Collision/Manifold.hpp, PlayRho/Collision/Shapes/ChainShape.hpp, PlayRho/Collision/Shapes/DiskShape.hpp, PlayRho/Collision/Shapes/EdgeShape.hpp, PlayRho/Collision/Shapes/MultiShape.hpp, PlayRho/Collision/Shapes/PolygonShape.hpp, PlayRho/Collision/Shapes/Shape.hpp, PlayRho/Collision/TimeOfImpact.hpp, PlayRho/Collision/WorldManifold.hpp, PlayRho/Common/BlockAllocator.cpp, PlayRho/Common/BoundedValue.hpp, PlayRho/Common/Fixed.hpp, PlayRho/Common/LengthError.hpp, PlayRho/Common/Math.hpp, PlayRho/Common/Range.hpp, PlayRho/Common/Settings.hpp, PlayRho/Common/StackAllocator.hpp, PlayRho/Common/Wider.hpp, PlayRho/Dynamics/Contacts/Contact.hpp, PlayRho/Dynamics/Contacts/ContactKey.hpp, PlayRho/Dynamics/Contacts/ContactSolver.hpp, PlayRho/Dynamics/Contacts/VelocityConstraint.hpp, PlayRho/Dynamics/Joints/JointKey.hpp, PlayRho/Dynamics/MovementConf.hpp, PlayRho/Rope/Rope.hpp
Changes to fix doxygen warnings.
Changes the doxygen configuration to treat warnings as errors and exit with non-zero exit status on any warnings.
Comment documentation changes to deal with some "compound" classes that aren't documented.
Should only improve documentation.
Issue #21.
=> For issue #21.

PlayRho/Collision/Manifold.hpp, PlayRho/Common/Settings.hpp, PlayRho/Dynamics/Contacts/Contact.hpp, PlayRho/Dynamics/StepConf.hpp, PlayRho/Dynamics/World.hpp, PlayRho/Dynamics/WorldCallbacks.hpp, UnitTests/ContactImpulsesList.cpp
Renames PlayRho *_t types to get rid of their _t suffix.
Shouldn't be any impacts/risks.
Do a search for ending with `_t = `. No matches means resolved.
Issue #84.
=> For issue #84.

HelloWorld/HelloWorld.cpp, PlayRho/Common/Units.hpp
Defines additional multiplication and division operator support beyond what boost::units already provides.
While this should have no impact at all when boost unit support isn't enabled, it should simplify documentation and make things easier for library users wishing to write code that's also compatible with enabling of boost units.
Issue #103.
=> For issue #103.

PlayRho/Collision/AABB.hpp, PlayRho/Collision/DynamicTree.cpp, PlayRho/Collision/DynamicTree.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, Testbed/Framework/Test.cpp, Testbed/Tests/DynamicTreeTest.hpp, Testbed/Tests/Tiles.hpp, UnitTests/DynamicTree.cpp, UnitTests/World.cpp
Basically refactors the `DynamicTree` class and related code.
More specifically...
- Changes `Dynamic::TreeNode` structure definition to use a union and… recognize its variant like uses more shaving off 8-bytes from its size.
- Changes DynamicTree's use of its TreeNode to include using placement new on it.
- Renames DynamicTree::size_type to DynamicTree::Size.
- Renames DynamicTree::next to DynamicTree::other.
- Adds DynamicTree::Height alias for Height related code.
- Refactors DynamicTree::InvalidIndex to being DynamicTree::GetInvalidSize() instead.
- Refactors DynamicTree::GetHeight() to being a free function instead.
- Refactors loops out from calling sites and moves it into called function.
- Cleanups and rebased to latest master code.
- Removes unnecessary std::move calls.
Could …
=> Refactors DynamicTree

Benchmark/BenchmarkMain.cpp, PlayRho/Collision/AABB.hpp, PlayRho/Collision/DynamicTree.cpp, PlayRho/Collision/DynamicTree.hpp, PlayRho/Common/ValueRange.hpp, PlayRho/Common/Vector.hpp, PlayRho/Common/Vector2D.hpp, Testbed/Framework/Test.cpp, Testbed/Framework/Test.hpp, Testbed/Tests/BodyTypes.hpp, Testbed/Tests/Confined.hpp, Testbed/Tests/FifteenPuzzle.hpp, Testbed/Tests/Tumbler.hpp, UnitTests/AABB.cpp, UnitTests/World.cpp
Adds a Tumbler like benchmark test.
Adds ValueRange based initializing copy constructor to AABB.
Fixes some unit mistakes.
Adds stream output operator support for ValueRange and Vector.
Adds drawing of DynamicTree's root AABB to Testbed when draw AABB is toggled on.
Adds max AABB stat collection to Testbed statistics output.
- Issue #136.
=> For issue #136.

PlayRho/Collision/WorldManifold.hpp, UnitTests/WorldManifold.cpp
Removes m_count member variable and replaces its functionality with valid-check lookup from m_separations. Reduces memory size from 52-bytes to 48-bytes.
Faster data transfers to/from caches.
=> Trims count from WorldManifold.

PlayRho/Collision/DynamicTree.cpp, PlayRho/Collision/DynamicTree.hpp, PlayRho/Dynamics/Contacts/ContactKey.cpp, PlayRho/Dynamics/FixtureProxy.hpp, PlayRho/Dynamics/World.cpp, Testbed/Framework/Test.cpp, Testbed/Tests/DynamicTreeTest.hpp, UnitTests/DynamicTree.cpp
Switches to nomenclature that makes more sense to me.
If the `DynamicTree` class is supposed to be usage agnostic, then calling things from it's perspective "leaf" makes more sense to me than calling things "proxy". "proxy" relates directly to the `FixtureProxy` class and while that's actually what the dynamic tree leafs are associating with in their user data, that's making the association in a way that contradicts calling it *user data*.
=> Changes DynamicTree nomenclature from using the term "proxy" to using "leaf"

PlayRho/Collision/DynamicTree.cpp, PlayRho/Collision/DynamicTree.hpp, PlayRho/Dynamics/World.cpp, Testbed/Framework/Test.cpp, Testbed/Tests/DynamicTreeTest.hpp, Testbed/Tests/Tiles.hpp, UnitTests/DynamicTree.cpp, UnitTests/World.cpp
- Refactors DynamicTree::ForEach into being a free function.
- Refactors DynamicTree::RayCast into being a free function.
- Refactors DynamicTree::Query into being a free function.
- Renames DynamicTree::GetUserData and SetUserData to GetLeafData and SetLeafData respectively.
- Replaces DynamicTree::LeafNode containing pointer to "user data" with a LeafData type alias.
- Move trivial method definitions from their .cpp file to the .hpp file for DynamicTree.
- Refactors implementation of DynamicTree::ComputeHeight(Size index) to be more robust.
- Refactors DynamicTree::ComputeHeight() into a free function.
=> Dynamic tree updates

PlayRho/Dynamics/Contacts/Contact.cpp, PlayRho/Dynamics/Contacts/Contact.hpp, PlayRho/Dynamics/World.cpp, UnitTests/Contact.cpp, UnitTests/DynamicTree.cpp, UnitTests/WorldManifold.cpp
Stores FixtureProxy* in Contact instead of Fixture* + child index, thereby saving 8-bytes per Contact.
=> For issue #150.

PlayRho/Collision/AABB.cpp, PlayRho/Collision/AABB.hpp, PlayRho/Dynamics/FixtureProxy.hpp, PlayRho/Dynamics/World.cpp, UnitTests/AABB.cpp, UnitTests/Contact.cpp, UnitTests/FixtureProxy.cpp, UnitTests/WorldManifold.cpp
Removes the AABB from the FixtureProxy. The AABB isn't necessary. This shaves off 16-bytes from each FixtureProxy.
=> Removes the AABB from the FixtureProxy.

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, HelloWorld/HelloWorld.cpp, PlayRho/Collision/AABB.hpp, PlayRho/Common/Intervals.hpp, PlayRho/Common/Transformation.hpp, PlayRho/Dynamics/Body.hpp, PlayRho/Dynamics/Contacts/Contact.hpp, PlayRho/Dynamics/Fixture.hpp, PlayRho/Dynamics/FixtureProxy.hpp, PlayRho/Dynamics/Joints/GearJoint.hpp, PlayRho/Dynamics/Joints/MotorJoint.cpp, PlayRho/Dynamics/Joints/MotorJoint.hpp, UnitTests/AABB.cpp, UnitTests/DistanceJoint.cpp, UnitTests/Fixture.cpp, UnitTests/FrictionJoint.cpp, UnitTests/GearJoint.cpp, UnitTests/MotorJoint.cpp, UnitTests/PulleyJoint.cpp, UnitTests/RevoluteJoint.cpp, UnitTests/RopeJoint.cpp, UnitTests/Transformation.cpp, UnitTests/WeldJoint.cpp, UnitTests/WheelJoint.cpp
Adds more unit test code. Also refactors AABB's use of `Interval<Length>` out to its own type alias.
Some previous changes had introduced new library code without adding corresponding unit test code. This rectifies that. Also adds unit test code for some formerly untested aspects of joints.
=> Adds more unit test code.

PlayRho/Dynamics/Joints/Joint.hpp, PlayRho/Dynamics/Joints/JointVisitor.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp
- Refactors out constant joint visitor code to ConstJointVisitor.
- Changes joint creation to throw on invalid arguments instead of returning nullptr.
- Refactors the World::Add(Joint*) method to no longer take bodies as part of its input parameter sequence.
=> Primarily refactors out constant joint visitor code to ConstJointVisitor

PlayRho/Dynamics/Contacts/VelocityConstraint.cpp, PlayRho/Dynamics/Contacts/VelocityConstraint.hpp, UnitTests/VelocityConstraint.cpp
Removes the caching of the sum of the inverse body mass from VelocityConstraint. The sum was only used in VelocityConstraint::GetPoint which is only called during VelocityConstraint construction and as such had limited use. Benchmark #s don't appear to be reliably effected by this change.
=> Removes the caching of the sum of the inverse body mass from VelocityConstraint

PlayRho/Dynamics/Fixture.hpp, Testbed/Framework/Main.cpp, UnitTests/Body.cpp
- Fixes double-free bug with Body::SetEnabled(false).
- Enables the body enable checkbox in the Testbed GUI.
- Adds unit test code to confirm issue/fix.
=> Fixes double-free bug with Body::SetEnabled(false).

PlayRho/Common/Math.hpp, PlayRho/Common/Position.hpp, PlayRho/Dynamics/Fixture.hpp, Testbed/Framework/DebugDraw.cpp, Testbed/Framework/DebugDraw.hpp, Testbed/Framework/Main.cpp, Testbed/Framework/Test.cpp, Testbed/Framework/Test.hpp, Testbed/Tests/SolarSystem.hpp, UnitTests/Angle.cpp
- Moves the camera global from Main.cpp into DebugDraw for wider usage.
- Exposes control of the StepConf::minStillTimeToSleep parameter to the Testbed UI.
- Provides an entity editor UI interface to shapes.
- Makes use of GetRevRotationalAngle to Testbed's DrawCorner code to fix missing arc seen in Distance Test.
- Updates the Testbed code for drawing center of masses to scale the segments based on the cubed root of the mass in question.
- Updates the bomb spawning code to better handle scales like that of the Solar System test.
- Updates the Solar System Testbed test to provide more info to users.
- Makes Fixture::GetProxies() public on seeing no reason to hide it.
- Adds more sanity checking of inputs.
- Adds GetRevRotationalAngle back since GetDelta doesn't do what's needed for things …
=> Misc updates 20171111

CMakeLists.txt
Disables installation of gtest and/or gmock when only installing PlayRho was requested.
- Issue #45.
=> For issue #45.

PlayRho/Collision/AABB.hpp, PlayRho/Common/Vector.hpp
Re-implements <= and >= for AABB and Vector using `std::mismatch` instead of `std::lexicographical_compare`.
- Issue #1 .
=> Fix assertions under debug build unit testing with Visual Studio.

Benchmark/BenchmarkMain.cpp, Benchmark/CMakeLists.txt, Benchmark/README.md, appveyor.yml
- Adds build instructions for the Benchmark application.
- Hides away BENCHMARK CMake options as advanced.
- Adds the ctime header to fix Visual C++ compiler error on not finding std::time.
- Switches from copy construction via braced initialization to parenthesis.
- Issue #214.
- Issue #215.
=> For issue #214 and issue #215.

PlayRho/Dynamics/Island.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp
- Simply abstracts the usage of std::vector<Body*> to a type alias of BodyStack.
- Updates documentation comment.
=> Trivial misc mods 2017112301

PlayRho/Collision/Simplex.hpp, PlayRho/Collision/TimeOfImpact.cpp, PlayRho/Common/Fixed.hpp, PlayRho/Common/Math.hpp, PlayRho/Dynamics/StepConf.hpp, PlayRho/Dynamics/World.cpp, Testbed/Tests/SolarSystem.hpp, UnitTests/CollideShapes.cpp, UnitTests/ContactSolver.cpp, UnitTests/Epsilon.cpp, UnitTests/MassData.cpp, UnitTests/PositionSolverManifold.cpp, UnitTests/Simplex.cpp, UnitTests/TimeOfImpact.cpp, UnitTests/UnitVec2.cpp, UnitTests/World.cpp
- Replaces duplicated code in favor of more generic code using templates.
- Gets more specific about what's available functionality from templates.
- Adds to the unit test coverage for UnitVec2 and TOI related code.
- Fixes bug in corner case detection code.
- Changes related to handling larger scales and better understanding of numerical limitations.
Issue #217.
=> For real concept 2017112701

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Collision/Shapes/FunctionalShapeVisitor.hpp, PlayRho/Dynamics/Joints/FunctionalJointVisitor.hpp, Testbed/Framework/Test.hpp
- Adds lambda accepting visitor implementations for JointVisitor and ShapeVisitor interfaces as perhaps a more convenient alternative for visiting joints and/or shapes.
- Issue #217.
=> For issue #217.

Benchmark/BenchmarkMain.cpp, Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Collision/AABB.cpp, PlayRho/Collision/DistanceProxy.cpp, PlayRho/Collision/DistanceProxy.hpp, PlayRho/Collision/Manifold.cpp, PlayRho/Collision/ShapeSeparation.cpp, PlayRho/Collision/ShapeSeparation.hpp, PlayRho/Common/Fixed.hpp, PlayRho/Common/Real.hpp, PlayRho/Common/Real.hpp.in, PlayRho/Common/Vector2.hpp, UnitTests/Angle.cpp, UnitTests/Body.cpp, UnitTests/CollideShapes.cpp, UnitTests/Contact.cpp, UnitTests/RevoluteJoint.cpp, UnitTests/TimeOfImpact.cpp
- Updates benchmarking application.
- Turns on use of optimization profiling.
- Adds a bit more tolerance for helping Fixed64 based Real pass more unit tests.
- Fixes bug in syntax that's only seen when boost units are enabled.
- Adds support for ranged looping over DistanceProxy's vertices and makes use of it.
- Fixes conflict with GetInvalid when Real = Fixed64.
- Switches to more generic syntax.
- Calls the non-stopping version of GetMaxSeparation since it's unlikely that'd help given this code typically called after detecting AABB overlap.
- Trivial grammatical change in documentation comment.
=> Misc changes 20171202

PlayRho/Common/Fixed.hpp, PlayRho/Common/Wider.hpp, PlayRho/Defines.hpp
Uses the definition of `__SIZEOF_INT128__` instead of `_WIN32` to determine whether the platform supports 128-bit integers. This define is used by clang and gcc and presumably only defined when 128-bit integers are in fact supported. So while this isn't perfect either, it's preferred over presuming 128-bit integer support exists unless _WIN32 is defined.
- Issue #241.
=> For issue #241

INSTALL.md
Updates documentation to deprecate building directly from provided Windows Visual Studio project files.
- For issue #228.
=> For issue #228.

PlayRho/Collision/Shapes/ChainShapeConf.cpp, PlayRho/Collision/Shapes/ChainShapeConf.hpp, PlayRho/Collision/Shapes/DiskShapeConf.hpp, PlayRho/Collision/Shapes/EdgeShapeConf.cpp, PlayRho/Collision/Shapes/EdgeShapeConf.hpp, PlayRho/Collision/Shapes/MultiShapeConf.cpp, PlayRho/Collision/Shapes/MultiShapeConf.hpp, PlayRho/Collision/Shapes/PolygonShapeConf.cpp, PlayRho/Collision/Shapes/PolygonShapeConf.hpp, PlayRho/Collision/Shapes/Shape.cpp, PlayRho/Collision/Shapes/Shape.hpp, PlayRho/Collision/Shapes/ShapeConf.hpp, PlayRho/Collision/WorldManifold.cpp, PlayRho/Dynamics/Contacts/Contact.cpp, PlayRho/Dynamics/Contacts/Contact.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, Testbed/Framework/Main.cpp, Testbed/Tests/Confined.hpp, Testbed/Tests/DistanceTest.hpp, Testbed/Tests/FifteenPuzzle.hpp, Testbed/Tests/JointsTest.hpp, Testbed/Tests/OneSidedPlatform.hpp, UnitTests/Body.cpp, UnitTests/ChainShape.cpp, UnitTests/DiskShape.cpp, UnitTests/MultiShape.cpp, UnitTests/Shape.cpp, UnitTests/World.cpp
- Changes the Shape class to make the vertex radius dependent on the child index.
- Adds default construction to Shape class. This makes it usable for types like std::vector.
- Issue #276.
=> Several changes to Shape class

Benchmark/BenchmarkMain.cpp
Adds more benchmarks oriented toward solving the mystery of why boost units appears to be slowing down simulations.
- For issue #281.
=> Adds benchmarks for solving why boost units slowing things down

PlayRho/Common/Math.cpp, PlayRho/Common/Math.hpp, PlayRho/Dynamics/Body.hpp, PlayRho/Dynamics/BodyConf.hpp, Testbed/Tests/Car.hpp, UnitTests/Body.cpp
- Adds new BodyConf builder convenience methods.
- Adds new free functions for getting and setting Body settings.
- Updates the Car Testbed Test/demo to enable car turning around via reflection transformations.
- Adds associated unit test code.
- Moves the GetContactRelVelocity implementation code into the Math.cpp file.
- Issue #287.
=> Changes for enabling car turning around in car Testbed test and more.

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Collision/DynamicTree.cpp, PlayRho/Collision/DynamicTree.hpp, PlayRho/Dynamics/IslandStats.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, PlayRho/Dynamics/WorldCallbacks.hpp, Testbed/Framework/DebugDraw.cpp, Testbed/Framework/Drawer.hpp, Testbed/Framework/Test.cpp, Testbed/Framework/Test.hpp, Testbed/Tests/BagOfDisks.hpp, Testbed/Tests/Bridge.hpp, Testbed/Tests/PolyShapes.hpp, Testbed/Tests/SolarSystem.hpp, Testbed/Tests/Tumbler.hpp, Testbed/Tests/Web.hpp, Testbed/Tests/iforce2d_TopdownCar.hpp, UnitTests/ArrayList.cpp, UnitTests/DynamicTree.cpp, UnitTests/Math.cpp, UnitTests/World.cpp
- Moves World::IslandSolverResults to IslandStats for issue #291.
- For issue #290: moves QueryAABB and QueryFixtureCallback out from World class and into DynamicTree.*.
- Lifts the acquisition of world.GetBodies() data out from multiple call sites in favor of using a saved value for it.
- Gets rid of some uses of PLAYRHO_CONSTEXPR outside of the PlayRho library in favor of directly using 'constexpr'.
- Issue #291.
- Issue #290.
=> Various changes 20180127

PlayRho/Common/Templates.hpp, PlayRho/Common/Vector.hpp, UnitTests/ChainShape.cpp, UnitTests/Vector.cpp
Transforms Vector <, <=, >, >= support to more generic lexicographical function objects operating over containers.
Vectors don't inherently have a natural singular concept of these comparisons anyway. Arguably it's more natural for them to use these comparisons based on magnitudes. But that fails to provide regularity with respect to equality - i.e. !(A < B) && !(B < A) should mean that A == B. In the case of using magnitudes, it doesn't.
=> Transforms Vector <, <=, >, >= support to more generic support

.travis.yml
Apparently the last changes weren't enough. After you pulled the stuff in, i noticed coveralls still not working. Seems the with all the recent changes in that squashed mega-commit some paths in travis changed. Seemed to have changed to an in-source-built or something like that.
Anyway - changed the paths in .travis.yml. Hopefully this will do it now.
https://travis-ci.org/ninnghazad/PlayRho/jobs/553746287
https://coveralls.io/builds/24347713
=> ... and another fix for travis.

Documentation/Doxyfile
Doxygen tagfiles can be used to link between doxygen documentations that use the same symbols (https://www.doxygen.nl/manual/external.html). I would like to link from API references of my project that uses PlayRho into PlayRho references. I will be able to do it once newly generated PlayRho.tag file is uploaded to gh-pages together with the rest of the documentation.
=> Doxyfile modification to generate tagfile.

Documentation/Doxyfile, PlayRho/Common/Version.cpp, PlayRho/Dynamics/Joints/PulleyJointConf.cpp, PlayRho/Dynamics/Joints/PulleyJointConf.hpp, Testbed/Framework/Main.cpp, Testbed/Tests/JointsTest.hpp, UnitTests/PulleyJoint.cpp, UnitTests/Version.cpp
- Fixes #365.
- Fixes an unreported issue with the Entity Editor in the Testbed where iterations couldn't be set separately for regular phase and TOI phase.
- Updates version to 0.11.1.
- Issue #365: Pulley joints don't appear to work anymore.
=> Bug fixes for 1.0 pre-release 0.11.1

PlayRho/Common/IndexingNamedType.hpp, PlayRho/Common/TypeInfo.hpp, PlayRho/Dynamics/BodyConf.hpp, PlayRho/Dynamics/Contacts/ContactSolver.cpp, PlayRho/Dynamics/Contacts/VelocityConstraint.cpp, PlayRho/Dynamics/Joints/Joint.cpp, PlayRho/Dynamics/WorldImpl.cpp, UnitTests/World.cpp, UnitTests/WorldImpl.cpp
- Changes towards using the more conventional `to_underlying` idea...
- Adds implementations of the C++23 to_underlying idea.
- Switches from using UnderlyingValue functions to using new
to_underlying functions.
- Deprecates the UnderlyingValue functions.
- Switches from using IndexingNamedType::get to using new to_underlying
functions.
- These changes also make it easier to eventually switch from using the
IndexingNamedType class to more simply/idiomatically just using opaque
scoped enumerations at least for types using integral underlying types -
this won't work for the `TypeID` type which uses a pointer type as its underlying type.
- Removes no longer relevant comments.
- Updates docs.
=> Updates 20210414

PlayRho/CMakeLists.txt
I can't build playrho shared build only.
It seems to be caused by CMakeLists.txt bug.
Nothing at all.
Only 1 line.
I build Playrho locally with `PLAYRHO_BUILD_SHARED=ON PLAYRHO_BUILD_STATIC=OFF`.
I am trying to create conan recipe for PlayRho.
https://github.com/conan-io/conan-center-index/pull/11728
This bug prevents conan-center-index's CI test of PlayRho.
=> fix target name in build shared

Testbed/Framework/Main.cpp
Avoids deprecated warnings in Testbed by switching to `to_underlying`.
- Issue #438.
=> Avoids deprecated warnings in Testbed by switching to to_underlying

Testbed/Framework/DebugDraw.cpp, Testbed/Framework/Main.cpp, Testbed/Framework/Test.cpp
Avoids insecure `*sprintf` functions.
- Issue #442.
=> Fix for issue #442: avoids insecure sprintf functions

Benchmark/CMakeLists.txt, HelloWorld/CMakeLists.txt, PlayRho/CMakeLists.txt, Testbed/CMakeLists.txt, UnitTests/CMakeLists.txt, UnitTests/World.cpp
Fixes installed headers to being cmake configured ones
1. Run `cmake --install PlayRhoBuild`.
1. Confirm an installed file like `/usr/local/include/PlayRho/Defines.hpp` contains a non-zero value for the project's major version.
=> Fixes installed headers to being cmake configured ones

.github/workflows/linux-debug.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, Build/xcode5/PlayRho.xcodeproj/project.pbxproj, CMakeLists.txt, INSTALL.md, PlayRho/CMakeLists.txt, PlayRho/Common/TypeInfo.hpp, PlayRho/Dynamics/Joints/GearJointConf.hpp, PlayRho/Dynamics/Joints/Joint.hpp, UnitTests/CMakeLists.txt, UnitTests/GearJoint.cpp, UnitTests/TypeInfo.cpp
Changes for exports/DLLs
- Updates workflow yml syntax.
- Explicitly sets gtest_hide_internal_symbols.
- Fixes TypeInfo to better support Windows shared linkage while still supporting the other platforms.
- Updates INSTALL.md.
(cherry picked from commit e081983316024880a7d12787a1be37d286bacb57)
=> Changes for exports/DLLs

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/CMakeLists.txt, PlayRho/Collision/Distance.cpp, PlayRho/Collision/DistanceProxy.cpp, PlayRho/Collision/DistanceProxy.hpp, PlayRho/Collision/DynamicTree.cpp, PlayRho/Collision/Shapes/ChainShapeConf.cpp, PlayRho/Collision/Shapes/ChainShapeConf.hpp, PlayRho/Collision/Shapes/Compositor.hpp, PlayRho/Collision/WorldManifold.hpp, PlayRho/Common/CheckedValue.hpp, PlayRho/Common/Math.cpp, PlayRho/Common/Math.hpp, PlayRho/Common/StackAllocator.hpp, PlayRho/Dynamics/WorldImpl.cpp, UnitTests/Math.cpp
I had these enabled in my development environments but had forgotten to add these to CMake. Thanks go to GitHub user "titofra" for pointing out that these were missing from CMake in their PR, #484.
Cleaner builds - in terms of compiler reported warnings/errors - by users including the PlayRho library.
The compile logs of the CI workflows.
Noticing that no warnings/errors are reported - after possibly addressing any that may now show up.
- #484.
=> Enables warnings by default for all compiles of the PlayRho library

PlayRho/Common/FlagGuard.hpp, PlayRho/Common/Templates.hpp, PlayRho/Common/Version.cpp, PlayRho/Common/Version.hpp, PlayRho/Dynamics/Joints/JointConf.hpp, UnitTests/DistanceJoint.cpp, UnitTests/FrictionJoint.cpp, UnitTests/GearJoint.cpp, UnitTests/MotorJoint.cpp, UnitTests/PrismaticJoint.cpp, UnitTests/PulleyJoint.cpp, UnitTests/RevoluteJoint.cpp, UnitTests/RopeJoint.cpp, UnitTests/TargetJoint.cpp, UnitTests/WeldJoint.cpp, UnitTests/WheelJoint.cpp
- Specify joint conf alignment.
- Stips `noexcept` from `GetBuildDetails` function which shouldn't have been marked that way.
- Address some warnings against reference data members detected by clang-tidy.
Code's less likely to fatally exit & clang-tidy will have less to complain about.
=> Some cleanups to address UB sanitizer & clang-tidy

PlayRho/Common/Math.hpp
Moves `ToSigned` from `playrho::d2` up to `playrho`.
- Issue #490.
=> Moves ToSigned out from playrho::d2 and properly into playrho

PlayRho/Common/Span.hpp, PlayRho/Common/Templates.hpp, PlayRho/Common/VertexSet.hpp
- Removes no longer needed functions `Data` + `Size`.
- Makes `Span` more `std::span` like.
=> Removes no longer needed functions Data+Size & makes Span more std::span

Library/include/playrho/Matrix.hpp, Library/include/playrho/Vector.hpp, Library/include/playrho/d2/Joint.hpp, Library/include/playrho/d2/Shape.hpp, Library/include/playrho/detail/underlying_type.hpp, Library/source/playrho/d2/AabbTreeWorld.cpp, UnitTests/Shape.cpp
- Moves more details under `detail` sub-namespace.
- Removes `SHAPE_USES_UNIQUE_PTR` macro in favor of using `unique_ptr` all the time.
=> Updates 20230929

.github/workflows/docs.yml
`cp` not same as `cp` between all two Unix. So maybe `rsync` more consistent. So trailing `/` honored.
=> Second try at pushing Doxygen API updates to gh-pages via CI

Benchmark/CMakeLists.txt, INSTALL.md, Library/include/playrho/d2/AabbTreeWorld.hpp, Library/include/playrho/d2/World.hpp, Library/include/playrho/d2/WorldConf.hpp, Library/include/playrho/pmr/PoolMemoryResource.hpp, Library/source/playrho/d2/AabbTreeWorld.cpp, Testbed/CMakeLists.txt, UnitTests/AabbTreeWorld.cpp, UnitTests/CMakeLists.txt, UnitTests/World.cpp, UnitTests/WorldConf.cpp
- Adds option to enable/disable resource stats collection to `WorldConf`.
- Adds a `pmr::StatsResource` data member to `AabbTreeWorld` to support stats collection.
- Adds `GetType` & `TypeCast` support to `World` - like `Joint` has.
- Updates `INSTALL.md` for new CMake `FetchContent` support that was previously added to application `CMakeLists.txt` files.
=> Updates 202310071

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, Library/CMakeLists.txt, Library/include/playrho/Contact.hpp, Library/include/playrho/Fixed.hpp, Library/include/playrho/FixedMath.hpp, Library/include/playrho/Math.hpp, Library/include/playrho/NonNegative.hpp, Library/include/playrho/ToiOutput.hpp, Library/include/playrho/Units.hpp, Library/include/playrho/d2/Sweep.hpp, Library/include/playrho/detail/Checked.hpp, Library/include/playrho/detail/CheckedMath.hpp, Library/include/playrho/detail/Templates.hpp, Library/source/playrho/Math.cpp, Library/source/playrho/d2/AabbTreeWorld.cpp, Library/source/playrho/d2/TimeOfImpact.cpp, Testbed/Framework/Main.cpp, UnitTests/Math.cpp, UnitTests/World.cpp
- Updates `Checked` type to support any `is_constructible_v` type conversion instead of only non-narrowing conversions.
- Adds direct support for some cmath functions (`abs` and `nextafter`) as `CheckedMath.hpp`.
- Removes implicit conversion from `Fixed.hpp` in an if-statement.
- Updates `FixedMath.hpp` to keep detail functions at top and adds some new math function support from `cmath` (`isinf` and `floor`).
- Updates `GetCircleVertices` from taking `unsigned` number of slices to taking `std::size_t`.
- Updates `GetCircleVertices` to reserve space before pushing elements to avoid having to relocate memory for larger numbers of slices.
- Adds new template helpers.
=> Updates 20231012

Library/include/playrho/StepStats.hpp, Library/source/playrho/d2/AabbTreeWorld.cpp, Library/source/playrho/d2/Body.cpp, UnitTests/StepStats.cpp, UnitTests/World.cpp
Basically moves contact updating out from being only done when the time delta is not zero so that both contacts and manifolds can be made available with a zero delta time call of the world `Step` function. Also adds more `==` & `!=` support - adding these for the `PreStepStats`, `RegStepStats`, and `ToiStepStats` types.
=> Updates 20231223

Library/include/playrho/Contact.hpp, Library/include/playrho/InvalidArgument.hpp, Library/include/playrho/ObjectPool.hpp, Library/include/playrho/d2/AabbTreeWorld.hpp, Library/include/playrho/d2/Body.hpp, Library/include/playrho/d2/Joint.hpp, Library/include/playrho/d2/Shape.hpp, Library/include/playrho/d2/World.hpp, Library/source/playrho/d2/AabbTreeWorld.cpp, Library/source/playrho/d2/Body.cpp, UnitTests/AabbTreeWorld.cpp, UnitTests/Body.cpp, UnitTests/Contact.cpp, UnitTests/World.cpp
- Addresses issue #561.
- Avoids further enlarging the `World` interface.
- Changes semantics of empty `Joint` and empty `Shape` objects to mean _is-destroyed_.
- Issue #561.
=> Updates 20240101

Library/include/playrho/d2/World.hpp, UnitTests/World.cpp
Finishes support for issue #561.
Also, renames some variables used in unit test code to help recognize them as being `*ID`-type related variables.
=> Adds IsDestroyed functions to complete their type support

Library/include/playrho/d2/Body.hpp, Library/include/playrho/d2/BodyConf.hpp, Library/include/playrho/d2/Transformation.hpp, Library/source/playrho/d2/Body.cpp, Library/source/playrho/d2/BodyConf.cpp, UnitTests/Body.cpp
=> Changes to address #560
