AUTHORS
Updates the AUTHORS file and tests out the GitHub pull request interface.
Should not impact anything.
=> Update AUTHORS file [ci skip]

Benchmark/BenchmarkMain.cpp, PlayRho/Collision/Distance.cpp, PlayRho/Collision/MassData.cpp, PlayRho/Collision/RayCastOutput.cpp, PlayRho/Collision/Simplex.hpp, PlayRho/Collision/TimeOfImpact.cpp, PlayRho/Common/Math.cpp, PlayRho/Common/Math.hpp, PlayRho/Dynamics/Contacts/ContactSolver.cpp, PlayRho/Dynamics/Joints/MouseJoint.cpp, PlayRho/Dynamics/Joints/PulleyJoint.cpp, Testbed/Tests/DistanceTest.hpp, Testbed/Tests/SensorTest.hpp, UnitTests/CollideShapes.cpp, UnitTests/ContactSolver.cpp, UnitTests/DiskShape.cpp, UnitTests/Epsilon.cpp, UnitTests/Fixed.cpp, UnitTests/MassData.cpp, UnitTests/Math.cpp, UnitTests/PositionSolverManifold.cpp, UnitTests/Rot.cpp, UnitTests/Simplex.cpp, UnitTests/TimeOfImpact.cpp, UnitTests/Vec2.cpp, UnitTests/World.cpp
Renames Math.hpp functions to be naming compliant with convention.
Collisions with any other changes being made at the same time to any of the same files.
Issue #48 .
=> For issue #48.

Benchmark/BenchmarkMain.cpp, PlayRho/Collision/AABB.cpp, PlayRho/Collision/AABB.hpp, PlayRho/Collision/DynamicTree.cpp, PlayRho/Collision/Shapes/Shape.hpp, PlayRho/Common/Math.hpp, PlayRho/Common/Position.hpp, PlayRho/Common/Units.hpp, PlayRho/Dynamics/Body.cpp, PlayRho/Dynamics/Body.hpp, PlayRho/Dynamics/Contacts/ContactSolver.cpp, PlayRho/Dynamics/StepConf.hpp, PlayRho/Dynamics/World.cpp, Testbed/Framework/Test.cpp, Testbed/Tests/BagOfDisks.hpp, Testbed/Tests/VaryingFriction.hpp, UnitTests/AABB.cpp, UnitTests/float.cpp
Updates code to better handle `-Ofast` compiler option and other non-IEEE754 compliant situations. Also gets benchmark code to compile for me.
Intended to improve the predictability of the library's behavior.
- Issue #18.
- Issue #41.
- Issue #42.
=> Various stuff

Testbed/README.md
Also tweak the wording elsewhere in the document to match.
Clarify the run procedure in MS Visual Studio
Enhances Documentation
Building on Windows is better described.
#16
#31
=> Add Windows CMake Build instructions

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Common/BlockAllocator.cpp, PlayRho/Common/DynamicMemory.cpp, PlayRho/Common/DynamicMemory.hpp, PlayRho/Common/GrowableStack.hpp, PlayRho/Common/Settings.hpp, PlayRho/Common/StackAllocator.cpp, PlayRho/Dynamics/World.cpp, PlayRho/Rope/Rope.cpp, Testbed/Tests/DumpShell.hpp
Moves C-style memory management code out from Settings and into its own files.
C-style dynamic memory management code won't be intermingling with settings code. There's no functional change.
For issue #58 .
=> For issue #58.

PlayRho/Common/InvalidArgument.hpp, PlayRho/Common/LengthError.hpp, PlayRho/Common/OptionalValue.hpp, PlayRho/Dynamics/Joints/DistanceJoint.cpp, PlayRho/Dynamics/Joints/DistanceJoint.hpp, PlayRho/Dynamics/Joints/FrictionJoint.cpp, PlayRho/Dynamics/Joints/FrictionJoint.hpp, PlayRho/Dynamics/Joints/GearJoint.cpp, PlayRho/Dynamics/Joints/GearJoint.hpp, PlayRho/Dynamics/Joints/Joint.hpp, PlayRho/Dynamics/Joints/MotorJoint.cpp, PlayRho/Dynamics/Joints/MotorJoint.hpp, PlayRho/Dynamics/Joints/MouseJoint.cpp, PlayRho/Dynamics/Joints/MouseJoint.hpp, PlayRho/Dynamics/Joints/PrismaticJoint.cpp, PlayRho/Dynamics/Joints/PrismaticJoint.hpp, PlayRho/Dynamics/Joints/PulleyJoint.cpp, PlayRho/Dynamics/Joints/PulleyJoint.hpp, PlayRho/Dynamics/Joints/RevoluteJoint.cpp, PlayRho/Dynamics/Joints/RevoluteJoint.hpp, PlayRho/Dynamics/Joints/RopeJoint.cpp, PlayRho/Dynamics/Joints/RopeJoint.hpp, PlayRho/Dynamics/Joints/WeldJoint.cpp, PlayRho/Dynamics/Joints/WeldJoint.hpp, PlayRho/Dynamics/Joints/WheelJoint.cpp, PlayRho/Dynamics/Joints/WheelJoint.hpp, UnitTests/MouseJoint.cpp
Basically removes extraneous code from Joint classes.
Minimal since only limited unit test code actually relies on this code.
Issue #62.
=> For issue 62

.travis.yml, Testbed/Tests/Tumbler.hpp
Attempts to reduce unnecessary Travis CI builds.
Maybe breaks the PR checks.
For issue #55 .
=> For issue 55

PlayRho/Dynamics/Joints/Joint.cpp
Tests if removing include <new> breaks the code
Breaking code
[Unnecessary includes in *.cpp](https://github.com/louis-langholtz/PlayRho/issues/73)
=> Unnecessary <new>

PlayRho/Collision/Collision.cpp, PlayRho/Collision/Manifold.cpp, PlayRho/Common/Fixed.hpp, PlayRho/Dynamics/Contacts/Contact.cpp, Testbed/Framework/Test.cpp, Testbed/Tests/DistanceTest.hpp, UnitTests/World.cpp
Resolves issue #10.
Effects step stats results. Improves Tumbler demo w.r.t. reducing squishyness.
Run the Testbed Tumbler demo and compare to images saved in issue #10.
Issue #10.
Boom!! Woot...
=> For squishy issue

appveyor.yml
Installs doxygen on AppVeyor and runs it.
AppVeyor builds may break during testing/refinement.
Issue #79.
=> For issue #79

CONTRIBUTING.md, Documentation/StyleGuide.md
Adds an initial coding style guide document.
Some documentation links might break.
Issue #2.
=> For issue #2.

PlayRho/Collision/Simplex.hpp, PlayRho/Collision/TimeOfImpact.hpp, PlayRho/Common/Math.hpp, PlayRho/Common/Settings.hpp
Fixes typos in comments
[Wrong comments issue](https://github.com/louis-langholtz/PlayRho/issues/74)
=> Fixed typos

Documentation/UserGuide.md, PlayRho/Collision/DistanceProxy.cpp, PlayRho/Collision/DistanceProxy.hpp, PlayRho/Collision/Manifold.hpp, PlayRho/Collision/Shapes/Shape.cpp, PlayRho/Collision/Shapes/Shape.hpp, PlayRho/Collision/Simplex.hpp, PlayRho/Collision/WorldManifold.hpp, PlayRho/Common/BlockAllocator.hpp, PlayRho/Common/BoundedValue.hpp, PlayRho/Common/Fixed.hpp, PlayRho/Common/Math.hpp, PlayRho/Common/Sweep.hpp, PlayRho/Common/Transformation.hpp, PlayRho/Common/Units.hpp, PlayRho/Dynamics/Island.hpp, PlayRho/Dynamics/World.hpp, Testbed/Tests/BagOfDisks.hpp
Provides an incremental update to these issues.
Hopefully only improves the User and API documentation.
- Issue #20.
- Issue #21.
=> For issue #20 and issue #21.

.clang-tidy, Documentation/Doxyfile, PlayRho/Collision/RayCastOutput.hpp, PlayRho/Collision/Shapes/ChainShape.hpp, PlayRho/Collision/Shapes/DiskShape.hpp, PlayRho/Collision/Shapes/EdgeShape.hpp, PlayRho/Collision/Shapes/PolygonShape.hpp, PlayRho/Collision/Shapes/Shape.hpp, PlayRho/Collision/Shapes/ShapeVisitor.hpp, PlayRho/Dynamics/Joints/Joint.cpp, PlayRho/Dynamics/Joints/Joint.hpp, PlayRho/Dynamics/World.cpp, Testbed/Framework/DebugDraw.hpp, UnitTests/Joint.cpp, UnitTests/UnitVec2.cpp, appveyor.yml
Adds graphviz as requirement for generating Doxygen docs. Also more document comment updates.
May cause issue if graphviz not available on CI host that's running doxygen.
- Issue #21.
=> For issue #21.

PlayRho/Common/ValueRange.hpp
For issue #124. Also optimizes single value constructor to avoid unnecessarily doing a minmax comparison.
Improved debugging of AABB structures.
- Issue #124.
=> For issue #124.

PlayRho/Collision/DynamicTree.cpp, PlayRho/Collision/DynamicTree.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, Testbed/Framework/Test.cpp, Testbed/Tests/Tiles.hpp, UnitTests/DynamicTree.cpp, UnitTests/World.cpp
Should resolve issue #129.
Better statistics.
- Issue #129.
=> For issue #129.

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Collision/Shapes/ChainShape.hpp, PlayRho/Collision/Shapes/DiskShape.hpp, PlayRho/Collision/Shapes/EdgeShape.hpp, PlayRho/Collision/Shapes/MultiShape.hpp, PlayRho/Collision/Shapes/PolygonShape.hpp, PlayRho/Collision/Shapes/Shape.cpp, PlayRho/Collision/Shapes/Shape.hpp, PlayRho/Collision/Shapes/ShapeDef.hpp, PlayRho/Common/Vector.hpp, PlayRho/Dynamics/Body.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, Testbed/Framework/Test.cpp, Testbed/Framework/Test.hpp, Testbed/Framework/TestEntry.cpp, Testbed/Tests/Confined.hpp, Testbed/Tests/FifteenPuzzle.hpp, UnitTests/DynamicTree.cpp, UnitTests/Vector.cpp, UnitTests/World.cpp
Adds another demo of polygons sliding on polygon surfaces.
Was harder than I had realized to come up with an appealing Testbed demo of "non-stick" polygon behavior. So I punted and just went for a Testbed demo that I wanted to see and came up with an implementation of the 15-puzzle.
- Issue #127.
- Issue #135.
=> For issue 127 and issue 135

PlayRho/Collision/AABB.cpp, PlayRho/Collision/AABB.hpp, PlayRho/Collision/DynamicTree.cpp, PlayRho/Collision/RayCastOutput.cpp, PlayRho/Collision/Shapes/DiskShape.hpp, PlayRho/Dynamics/Fixture.cpp, PlayRho/Dynamics/Fixture.hpp, PlayRho/Dynamics/World.cpp, Testbed/Framework/Main.cpp, Testbed/Tests/DynamicTreeTest.hpp, UnitTests/AABB.cpp, UnitTests/DiskShape.cpp, UnitTests/World.cpp
Replaces AABB methods with free functions.
- Issue #140.
=> For issue #140.

Benchmark/BenchmarkMain.cpp, Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Collision/AABB.hpp, PlayRho/Common/ValueRange.hpp, UnitTests/AABB.cpp, UnitTests/ValueRange.cpp
Adds support for lexicographical compare of ValueRange and AABB classes.
- Issue #142.
=> For issue #142.

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Dynamics/Joints/WeldJointDef.hpp, PlayRho/Dynamics/WorldCallbacks.hpp, Testbed/Framework/TestEntry.cpp, Testbed/Tests/Breakable.hpp, Testbed/Tests/BreakableTwo.hpp, UnitTests/ContactImpulsesList.cpp
Adds a new second "Breakable" demo and associated code.
- Issue #139.
=> For issue 139.

Benchmark/BenchmarkMain.cpp, PlayRho/Collision/WorldManifold.hpp, PlayRho/Common/Units.hpp
- Fixes Units math ops to be constexpr as intended.
- Adds more benchmark tests.
=> Two changes.

Benchmark/BenchmarkMain.cpp, Testbed/Tests/AddPair.hpp
Adds an implementation of the AddPair demo to the benchmarking suite.
=> Adds an implementation of the AddPair demo to the benchmarking suite.

PlayRho/Common/Interval.hpp, PlayRho/Common/Math.hpp
Fixes Interval's Intersect method.
=> Fix for interval intersect

Benchmark/BenchmarkMain.cpp, PlayRho/Collision/AABB.cpp, PlayRho/Collision/AABB.hpp, PlayRho/Collision/DynamicTree.cpp, PlayRho/Collision/DynamicTree.hpp, PlayRho/Collision/Manifold.hpp, PlayRho/Dynamics/Body.cpp, PlayRho/Dynamics/Body.hpp, PlayRho/Dynamics/BodyAtty.hpp, PlayRho/Dynamics/Contacts/Contact.cpp, PlayRho/Dynamics/Contacts/Contact.hpp, PlayRho/Dynamics/Contacts/ContactKey.cpp, PlayRho/Dynamics/Contacts/ContactKey.hpp, PlayRho/Dynamics/Contacts/PositionConstraint.hpp, PlayRho/Dynamics/Fixture.cpp, PlayRho/Dynamics/Fixture.hpp, PlayRho/Dynamics/FixtureAtty.hpp, PlayRho/Dynamics/FixtureProxy.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, PlayRho/Dynamics/WorldDef.hpp, Testbed/Framework/Test.cpp, Testbed/Framework/TestEntry.cpp, UnitTests/Contact.cpp, UnitTests/DynamicTree.cpp, UnitTests/FixtureProxy.cpp, UnitTests/Manifold.cpp, UnitTests/PositionConstraint.cpp, UnitTests/World.cpp, UnitTests/WorldManifold.cpp
While these changes appear to improve performance on most benchmarks related to them, my more pressing motivation for committing this code is to add it to source code control for wider consideration and posterity. It demonstrates for instance another way to balance what keeps record of what between broad phase and narrow phase data. Recognizing this sort of flexibility can hopefully prove useful w.r.t. hardware specific optimizations.
=> Various changes related to refactoring FixtureProxy and the DynamicTree classes

PlayRho/Collision/Manifold.cpp, PlayRho/Common/Math.hpp, PlayRho/Dynamics/Contacts/BodyConstraint.hpp
=> A few miscellaneous tweaks.

appveyor.yml
- See about getting the syntax to do as intended.
=> For issue #109: AppVeyor built products not archived

appveyor.yml
Adds a limit to what branches are built in the hopes that this will actually do the intended actions (and only the intended actions).
=> For issue #88: continuous-integration/appveyor/branch check

Testbed/Framework/Test.cpp, Testbed/Framework/imgui.h
=> Cleanup testbed warnings.

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Common/RealConstants.hpp, PlayRho/Common/Units.hpp, PlayRho/Dynamics/Body.hpp, Testbed/Framework/DebugDraw.hpp, Testbed/Framework/Main.cpp, Testbed/Framework/Test.cpp, Testbed/Framework/Test.hpp, Testbed/Framework/TestEntry.cpp, Testbed/Framework/imgui.h, Testbed/Tests/DistanceTest.hpp, Testbed/Tests/FifteenPuzzle.hpp, Testbed/Tests/Prismatic.hpp, Testbed/Tests/SliderCrank.hpp, Testbed/Tests/SolarSystem.hpp, UnitTests/Units.cpp
- Adds new real constants to RealConstants.hpp.
- Adds and makes use of more user defined literals for units.
- Adds and makes use of min and max delta-t settings as well as camera settings.
- Extracts component UI code out to their own functions.
- Adds TooltipContext, and IdContext RAII classes and a ShowTooltip convenience function and makes use of these.
- Filters mouse inputs more selectively so tests don't get clicks meant for UI.
- Refactors statistics output for selected fixtures to leverage ImGui more and split that code out to its own functions.
- Adds unit test code for new unit literals.
=> Initial commit of a Testbed model of the solar system:

INSTALL.md, README.md
Updates doc files.
Should be none.
=> Minor documentation updates.

README.md
=> Fix URL linkage.

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Common/Acceleration.hpp, PlayRho/Common/Math.hpp, PlayRho/Dynamics/Body.cpp, PlayRho/Dynamics/Body.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, Testbed/Tests/SolarSystem.hpp, UnitTests/Acceleration.cpp, UnitTests/Body.cpp, UnitTests/World.cpp
Refactors some re-usable code out from Solar System Testbed and in to the library. Adds some associated unit testing for good measure.
=> Refactors some re-usable code out from Solar System Testbed and in to the library.

PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, Testbed/Tests/SolarSystem.hpp, UnitTests/World.cpp
Adds  camera following planet capability to Solar System demo.
=> Adds  camera following planet capability to Solar System demo.

Documentation/PhysicalUnits.md
=> Update physical units md

PlayRho/Collision/IndexPair.hpp, PlayRho/Collision/MassData.cpp, PlayRho/Collision/Simplex.hpp, PlayRho/Common/Math.hpp, PlayRho/Common/Matrix.hpp, PlayRho/Common/Templates.hpp, PlayRho/Common/UnitVec2.hpp, PlayRho/Common/Vector.hpp, PlayRho/Common/Vector2.hpp, PlayRho/Common/Vector3.hpp, PlayRho/Dynamics/Body.cpp, PlayRho/Dynamics/Joints/Joint.cpp, UnitTests/ArrayList.cpp, UnitTests/MassData.cpp, UnitTests/Math.cpp, UnitTests/PolygonShape.cpp, UnitTests/Simplex.cpp, UnitTests/Vector.cpp
=> Vector related changes

PlayRho/Common/Vector.hpp
Fixes documentation for Vector division.
=> Fixes documentation for Vector division.

PlayRho/Common/Math.hpp, PlayRho/Common/UnitVec2.hpp, PlayRho/Common/Vector.hpp, UnitTests/Vec2.cpp, UnitTests/Vec3.cpp
Generalize cross product functions
=> Generalize cross product functions

PlayRho/Collision/Manifold.cpp, UnitTests/Math.cpp
Adds in intermediary variables for debugging and adds unit test code to ensure Clamp works as its documented/expected to.
=> Just a couple of minor tweaks.

PlayRho/Collision/RayCastOutput.hpp, PlayRho/Collision/Shapes/Shape.hpp, PlayRho/Common/BoundedValue.hpp, PlayRho/Common/Math.hpp, PlayRho/Common/RealConstants.hpp, PlayRho/Common/Units.hpp, PlayRho/Dynamics/Body.hpp, PlayRho/Dynamics/Contacts/Contact.hpp, PlayRho/Dynamics/Fixture.hpp, PlayRho/Dynamics/Joints/Joint.hpp, PlayRho/Dynamics/World.hpp, PlayRho/PlayRho.hpp
Updates doxygen documentation and adds a new PhysicalEntities documentation module.
- Issue #21 
- Issue #81
=> For issue #21 and issue #81.

Benchmark/BenchmarkMain.cpp, PlayRho/Common/Math.hpp, PlayRho/Common/Position.hpp, PlayRho/Common/Sweep.hpp, PlayRho/Common/Units.hpp, PlayRho/Dynamics/Contacts/Contact.cpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, UnitTests/Angle.cpp, UnitTests/Sweep.cpp, UnitTests/World.cpp
Applies angle normalization to every updating body every step.
- Issue #152.
=> For issue #152.

PlayRho/Collision/Manifold.hpp, PlayRho/Common/Vector2.hpp, PlayRho/Common/Vector3.hpp, PlayRho/Dynamics/Contacts/ContactSolver.cpp, PlayRho/Dynamics/Contacts/VelocityConstraint.cpp, PlayRho/Dynamics/Contacts/VelocityConstraint.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/WorldCallbacks.hpp, UnitTests/VelocityConstraint.cpp
Shrinks VelocityConstraint another 8-bytes.
=> More units and datadensity

PlayRho/Common/Math.cpp, PlayRho/Common/Math.hpp, PlayRho/Dynamics/Contacts/Contact.cpp, PlayRho/Dynamics/Joints/MotorJoint.cpp, PlayRho/Dynamics/World.cpp, Testbed/Framework/Main.cpp, Testbed/Framework/Test.cpp, Testbed/Tests/JointsTest.hpp, UnitTests/Angle.cpp, UnitTests/World.cpp
- Rolls back changes related to angle normalization to restore joints working at the expense of having unbounded angles again.
- Renames GetRevRotationalAngle to GetDelta.
- Adds more unit testing.
- Increases Entity Editor interface to underlying data structures.
=> For issue #152:

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Collision/DynamicTree.cpp, PlayRho/Collision/Manifold.hpp, PlayRho/Common/UnitVec2.hpp, PlayRho/Common/Vector.hpp, PlayRho/Dynamics/Body.cpp, PlayRho/Dynamics/Contacts/PositionConstraint.hpp, PlayRho/Dynamics/Contacts/VelocityConstraint.cpp, PlayRho/Dynamics/Fixture.cpp, PlayRho/Dynamics/Fixture.hpp, PlayRho/Dynamics/Joints/Joint.cpp, PlayRho/Dynamics/Joints/MouseJoint.cpp, PlayRho/Dynamics/Joints/MouseJoint.hpp, PlayRho/Dynamics/Joints/PulleyJoint.hpp, PlayRho/Dynamics/Joints/WheelJoint.cpp, PlayRho/Dynamics/Joints/WheelJoint.hpp, PlayRho/Dynamics/World.cpp
Increases compiler warning level and fixes newly recognized warnings.
=> Increases compiler warning level and fixes newly recognized warnings.

Benchmark/BenchmarkMain.cpp, PlayRho/Common/OptionalValue.hpp, PlayRho/Dynamics/Joints/JointType.cpp, UnitTests/Math.cpp, UnitTests/Units.cpp, UnitTests/float.cpp
- Updates for building on Windows MS VS.
- Updates for benchmarking various primitives for multi threading.
=> Updates for windows and more

Testbed/Tests/AddPair.hpp, Testbed/Tests/BreakableTwo.hpp, Testbed/Tests/HeavyOnLightTwo.hpp, Testbed/Tests/JointsTest.hpp, Testbed/Tests/SolarSystem.hpp
- Changes to work around MS Visual C++ seemingly doing const propagating copy elision of brace-initialized objects and erroring out.
=> Changes to deal with MS Visual C++ strangeness.

UnitTests/CMakeLists.txt
Attempts to implement suggestions from GitHub user emptyVoid. For details, see: https://github.com/louis-langholtz/PlayRho/issues/1#issuecomment-329717878
- Issue #1.
=> For issue #1.

Testbed/Framework/Main.cpp, Testbed/Tests/VaryingRestitution.hpp, Testbed/Tests/iforce2d_Trajectories.hpp, appveyor.yml
First attempt to get Testbed building as part of appveyor CI.
- Issue #211.
=> For issue #211.

Benchmark/BenchmarkMain.cpp, PlayRho/Collision/RayCastOutput.cpp, PlayRho/Collision/TimeOfImpact.cpp, PlayRho/Collision/TimeOfImpact.hpp, PlayRho/Common/Fixed.hpp, PlayRho/Common/Math.hpp, PlayRho/Common/Sweep.hpp, PlayRho/Common/UnitVec2.cpp, PlayRho/Common/UnitVec2.hpp, PlayRho/Common/Units.hpp, PlayRho/Dynamics/Joints/DistanceJoint.cpp, PlayRho/Dynamics/Joints/PulleyJoint.cpp, PlayRho/Dynamics/Joints/RopeJoint.cpp, PlayRho/Dynamics/StepConf.hpp, Testbed/Tests/iforce2d_TopdownCar.hpp, UnitTests/TimeOfImpact.cpp, UnitTests/UnitVec2.cpp, UnitTests/World.cpp
- Adds more benchmark tests.
- Tweaks GetToiViaSat to provide more robustness and more feedback on return state which seems to have resulted in more expected results in the World HeavyOnLight unit test.
- Tweaks unit vector code.
- Updates unit tests.
=> Various changes:

Testbed/Framework/Main.cpp, Testbed/Framework/Test.cpp, Testbed/Framework/Test.hpp, Testbed/Tests/SolarSystem.hpp
Adds configurability to solar system demo for much larger bomb sizes and densities.
- Issue #217.
- Issue #225.
=> For issue #217 and issue #225.

PlayRho/Collision/Shapes/Shape.hpp, PlayRho/Common/Fixed.hpp, PlayRho/Common/Real.hpp, PlayRho/Common/Real.hpp.in, PlayRho/Common/RealConstants.hpp, PlayRho/Dynamics/Joints/GearJoint.cpp, PlayRho/Dynamics/Joints/GearJoint.hpp, PlayRho/Dynamics/Joints/Joint.hpp, UnitTests/GearJoint.cpp, UnitTests/World.cpp
- Adds documentation comments regarding use of visitor pattern.
- Updates documentation comments to more thoroughly explain what types can be used for the Real type alias.
- Adds validity check for GearJointDef parameters and unit test code to confirm.
- Issue #217.
=> For issue 217 20171129

appveyor.yml
See if install graphviz.portable improves matters on AppVeyor's doxygen build effort.
- Issue #233.
=> For issue #233: dot failing on AppVeyor.

PlayRho/Collision/TimeOfImpact.cpp, PlayRho/Collision/TimeOfImpact.hpp, UnitTests/TimeOfImpact.cpp
- Gets more precise about functionality.
=> Updates TOI documentation, implementation, and unit testing

PlayRho/Dynamics/Body.cpp, UnitTests/Body.cpp
Changes Body::SetAcceleration code to avoid waking bodies unless acceleration increased or changed direction.
- Issue #246.
=> For issue #246.

Benchmark/BenchmarkMain.cpp, appveyor.yml
- Changes to try and fix appveyor's ability to use dot when generating doxygen documentation.
- Adds in more benchmark tests and possibilities.
=> Misc changes 20171219

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Dynamics/StepStats.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, Testbed/Framework/Test.cpp, Testbed/Framework/Test.hpp, UnitTests/RayCastOutput.cpp, UnitTests/StepConf.cpp, UnitTests/StepStats.cpp
- Adapts unit test code for StepStats for when USE_BOOST_UNITS is defined.
- Adds more unit testing of RayCastOutput.
- Adds more tooltip info.
- Plums the max-simultaneous contacts count through to the UI.
- Refactors World::GetSoonestContacts into World::GetSoonestContact.
- Updates documentation comments specific to StepStats.
- Adds unit testing specific to StepStats.
=> Misc changes 20171220

PlayRho/Collision/Distance.hpp, PlayRho/Collision/Manifold.cpp, PlayRho/Collision/Manifold.hpp, PlayRho/Collision/SeparationFinder.cpp, PlayRho/Collision/SeparationFinder.hpp, PlayRho/Collision/Shapes/ChainShapeConf.hpp, PlayRho/Dynamics/Joints/RopeJointDef.hpp, UnitTests/BlockAllocator.cpp, UnitTests/FrictionJoint.cpp, UnitTests/RevoluteJoint.cpp, UnitTests/RopeJoint.cpp
- Updates documentation comments to make more use of available images.
- Changes for increasing unit test code coverage.
=> Misc changes 20171221

PlayRho/Collision/Manifold.cpp, PlayRho/Collision/Simplex.cpp, PlayRho/Collision/TimeOfImpact.cpp, PlayRho/Dynamics/Joints/DistanceJoint.hpp, PlayRho/Dynamics/Joints/Joint.hpp, PlayRho/Dynamics/Joints/MouseJoint.cpp, PlayRho/Dynamics/Joints/MouseJoint.hpp, PlayRho/Dynamics/Joints/PulleyJoint.cpp, PlayRho/Dynamics/Joints/PulleyJoint.hpp, UnitTests/DistanceJoint.cpp, UnitTests/GearJoint.cpp, UnitTests/MotorJoint.cpp, UnitTests/MouseJoint.cpp, UnitTests/PrismaticJoint.cpp, UnitTests/PulleyJoint.cpp, UnitTests/Simplex.cpp
=> Increases unit testing.

PlayRho/Dynamics/Contacts/PositionSolverManifold.cpp, PlayRho/Dynamics/Joints/Joint.cpp, PlayRho/Dynamics/Joints/JointType.cpp, PlayRho/Dynamics/Joints/PulleyJointDef.hpp, PlayRho/Dynamics/Joints/RevoluteJoint.cpp, PlayRho/Dynamics/Joints/RevoluteJoint.hpp, PlayRho/Dynamics/Joints/WeldJoint.cpp, PlayRho/Dynamics/World.cpp, UnitTests/Body.cpp, UnitTests/PositionSolverManifold.cpp, UnitTests/PrismaticJoint.cpp, UnitTests/PulleyJoint.cpp, UnitTests/RevoluteJoint.cpp, UnitTests/WeldJoint.cpp, UnitTests/World.cpp
Changes to increase unit test code coverage towards exceeding 97%.
- Issue #254.
=> For issue 254.

PlayRho/Collision/DynamicTree.cpp, PlayRho/Collision/DynamicTree.hpp, PlayRho/Collision/Simplex.cpp, PlayRho/Dynamics/Joints/WheelJoint.hpp, UnitTests/Contact.cpp, UnitTests/DynamicTree.cpp, UnitTests/Manifold.cpp, UnitTests/PolygonShape.cpp, UnitTests/WheelJoint.cpp, UnitTests/WorldManifold.cpp
Increasing unit test coverage beyond 98%.
- Issue #258.
=> For issue #258

PlayRho/Collision/AABB.cpp, PlayRho/Common/BoundedValue.hpp, PlayRho/Common/Fixed.hpp, PlayRho/Common/FixedMath.hpp, PlayRho/Common/Real.hpp, PlayRho/Common/Real.hpp.in, UnitTests/Fixed.cpp, UnitTests/RayCastOutput.cpp
Eliminates uses of floating point support in Fixed math functions.
I'm happiest about the sin/cos implementations as these seem very practically convergent and least happy about log.
- Issue #261.
=> For issue #261.

PlayRho/Collision/Shapes/ShapeConf.hpp, PlayRho/Dynamics/BodyConf.hpp, PlayRho/Dynamics/FixtureConf.hpp, PlayRho/Dynamics/Joints/DistanceJointConf.hpp, PlayRho/Dynamics/Joints/FrictionJointConf.hpp, PlayRho/Dynamics/Joints/GearJointConf.hpp, PlayRho/Dynamics/Joints/JointConf.hpp, PlayRho/Dynamics/Joints/MotorJointConf.hpp, PlayRho/Dynamics/Joints/MouseJointConf.hpp, PlayRho/Dynamics/Joints/PrismaticJointConf.hpp, PlayRho/Dynamics/Joints/PulleyJointConf.hpp, PlayRho/Dynamics/Joints/RevoluteJoinConf.hpp, PlayRho/Dynamics/Joints/RopeJointConf.hpp, PlayRho/Dynamics/Joints/WeldJointConf.hpp, PlayRho/Dynamics/Joints/WheelJointConf.hpp, PlayRho/Dynamics/WorldConf.hpp
Fixes include guards for files containing configuration classes.
=> Fixes include guards for files containing configuration classes.

PlayRho/Collision/DynamicTree.cpp, PlayRho/Collision/DynamicTree.hpp, PlayRho/Collision/RayCastOutput.cpp, PlayRho/Collision/RayCastOutput.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, UnitTests/Body.cpp, UnitTests/World.cpp
- Adds more unit testing of ray casting code.
- Issue #258.
=> For issue #258.

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Collision/TimeOfImpact.cpp, PlayRho/Collision/TimeOfImpact.hpp, PlayRho/Common/Velocity.cpp, PlayRho/Common/Velocity.hpp, PlayRho/Dynamics/BodyAtty.hpp, PlayRho/Dynamics/ContactAtty.hpp, PlayRho/Dynamics/ContactImpulsesList.cpp, PlayRho/Dynamics/ContactImpulsesList.hpp, PlayRho/Dynamics/Contacts/ContactSolver.cpp, PlayRho/Dynamics/Contacts/ContactSolver.hpp, PlayRho/Dynamics/Contacts/VelocityConstraint.cpp, PlayRho/Dynamics/Contacts/VelocityConstraint.hpp, PlayRho/Dynamics/FixtureAtty.hpp, PlayRho/Dynamics/StepStats.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/WorldCallbacks.hpp, PlayRho/Dynamics/WorldConf.hpp, Testbed/Framework/Test.hpp, UnitTests/ContactImpulsesList.cpp, UnitTests/World.cpp
- Pulls code out from World.cpp and into other files.
- Code cleanups towards trimming down World.cpp.
- Issue #272.
=> For issue #272.

PlayRho/Common/Math.hpp, PlayRho/Common/UnitVec.hpp, UnitTests/Math.cpp, UnitTests/UnitVec.cpp
Adds function to generate reflection matrices for issue #285.
- Issue #285.
=> Adds function to generate reflection matrices for issue #285.

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Dynamics/Body.cpp, PlayRho/Dynamics/Fixture.cpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, PlayRho/Dynamics/WorldAtty.hpp, UnitTests/Body.cpp, UnitTests/World.cpp
Moves World methods for Body & Fixture classes into new WorldAtty class.
- Issue #293.
=> Moves World methods for Body & Fixture classes into new WorldAtty class.

PlayRho/Collision/Manifold.cpp, PlayRho/Collision/Manifold.hpp, PlayRho/Common/Velocity.hpp, PlayRho/Dynamics/Body.cpp, PlayRho/Dynamics/Body.hpp, PlayRho/Dynamics/Contacts/BodyConstraint.hpp, PlayRho/Dynamics/Joints/PrismaticJoint.cpp, PlayRho/Dynamics/MovementConf.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, UnitTests/Body.cpp, UnitTests/CollideShapes.cpp, UnitTests/DynamicTree.cpp, UnitTests/PrismaticJoint.cpp, UnitTests/World.cpp
Removes fixtures and bodies from proxy processing queues before deletion.
- Issue #306.
=> For issue 306 and more

PlayRho/Collision/Manifold.cpp, PlayRho/Collision/Manifold.hpp, PlayRho/Common/Units.hpp, UnitTests/CollideShapes.cpp, UnitTests/FrictionJoint.cpp, UnitTests/GearJoint.cpp, UnitTests/Manifold.cpp, UnitTests/TargetJoint.cpp
Adds unit test code towards >99% unit test coverage.
- Issue #268.
=> For issue 268 20180325

PlayRho/Dynamics/Joints/RopeJoint.cpp, PlayRho/Dynamics/World.hpp, UnitTests/FrictionJoint.cpp, UnitTests/MotorJoint.cpp, UnitTests/RopeJoint.cpp, UnitTests/WeldJoint.cpp, UnitTests/WheelJoint.cpp, UnitTests/World.cpp
For issue #268: Not yet 99% unit test coverage
Issue #268.
=> For issue #268: Not yet 99% unit test coverage

PlayRho/Collision/TimeOfImpact.cpp, PlayRho/Common/Math.hpp, PlayRho/Common/UnitVec.cpp, PlayRho/Common/UnitVec.hpp, PlayRho/Common/Units.hpp, PlayRho/Dynamics/Joints/DistanceJoint.cpp, PlayRho/Dynamics/Joints/PulleyJoint.cpp, PlayRho/Dynamics/Joints/RopeJoint.cpp, Testbed/Framework/Main.cpp, Testbed/Framework/Test.cpp, Testbed/Framework/Test.hpp, UnitTests/PrismaticJoint.cpp, UnitTests/RopeJoint.cpp, UnitTests/TimeOfImpact.cpp
Adds more configurability to the Testbed and adds more unit testing.
- Issue #310
=> Updates 2018040100

PlayRho/Collision/DynamicTree.cpp, PlayRho/Collision/DynamicTree.hpp, PlayRho/Common/Templates.hpp, PlayRho/Common/Units.hpp, Testbed/Framework/Main.cpp, Testbed/Framework/Test.cpp, Testbed/Framework/Test.hpp, UnitTests/DynamicTree.cpp, UnitTests/Manifold.cpp, UnitTests/World.cpp
Updates the dynamic tree code and associated Testbed and unit test functions.
=> Updates 20180512

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Common/BlockAllocator.cpp, PlayRho/Common/StackAllocator.cpp, PlayRho/Common/Units.hpp, PlayRho/Dynamics/Body.cpp, PlayRho/Dynamics/Body.hpp, PlayRho/Dynamics/BodyAtty.hpp, PlayRho/Dynamics/Contacts/Contact.cpp, PlayRho/Dynamics/Fixture.cpp, PlayRho/Dynamics/Joints/Joint.cpp, PlayRho/Dynamics/Joints/MotorJoint.cpp, PlayRho/Dynamics/Joints/MotorJoint.hpp, PlayRho/Dynamics/World.cpp, Testbed/Framework/Main.cpp, Testbed/Framework/Test.cpp, Testbed/Framework/Test.hpp, Testbed/Framework/TestEntry.cpp, Testbed/Tests/Breakable.hpp, Testbed/Tests/MotorJoint.hpp, Testbed/Tests/MotorJoint2.hpp, Testbed/Tests/Tumbler.hpp, UnitTests/DynamicTree.cpp
This PR fixes two bugs found in the `MotorJoint` code. Also updates and improves other things including the Testbed. See related commit messages for details.
- Issue #315 : From Box2D: Motor joint appears to have non-physical behavior
=> Motorjoint updates 20180520

Changes.md, INSTALL.md, README.md
Updates documentation to reflect move to C++17 standard.
=> Updates documentation to reflect move to C++17 standard.

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, UnitTests/Transformation.cpp
- Removes unused variable.
- Updates MacOS deployment target to get needed C++ support for newer features.
=> Couple of trivial updates.

Build/vs2017/HelloWorld.vcxproj, Build/vs2017/PlayRho.vcxproj, Build/vs2017/Testbed.vcxproj, Documentation/Doxyfile, PlayRho/Collision/AABB.cpp, PlayRho/Collision/AABB.hpp, PlayRho/Collision/MassData.cpp, PlayRho/Collision/RayCastOutput.cpp, PlayRho/Collision/Simplex.cpp, PlayRho/Common/Acceleration.hpp, PlayRho/Common/DynamicMemory.hpp, PlayRho/Common/Math.cpp, PlayRho/Common/Math.hpp, PlayRho/Common/UnitVec.hpp, PlayRho/Common/Vector.hpp, PlayRho/Common/Velocity.hpp, PlayRho/Dynamics/Body.cpp, UnitTests/DiskShape.cpp, UnitTests/MultiShape.cpp, UnitTests/TimeOfImpact.cpp, UnitTests/UnitVec.cpp, UnitTests/World.cpp, appveyor.yml
=> Switches to using precomputed reciprocal math.

PlayRho/Dynamics/Joints/Joint.hpp, PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, PlayRho/Dynamics/WorldBody.cpp, PlayRho/Dynamics/WorldBody.hpp, PlayRho/Dynamics/WorldContact.hpp, PlayRho/Dynamics/WorldFixture.hpp, PlayRho/Dynamics/WorldImpl.cpp, PlayRho/Dynamics/WorldImpl.hpp, PlayRho/Dynamics/WorldImplBody.cpp, PlayRho/Dynamics/WorldImplBody.hpp, PlayRho/Dynamics/WorldImplFixture.cpp, PlayRho/Dynamics/WorldImplFixture.hpp, PlayRho/Dynamics/WorldJoint.cpp, PlayRho/Dynamics/WorldJoint.hpp, Testbed/Framework/Main.cpp, Testbed/Framework/Main.cpp-updated, UnitTests/WorldBody.cpp
More cleanups. For an issue and for docs & unit test improvements.
- Issue #355.
=> Issue fix and doc + unit tests improvements

CMakeLists.txt, PlayRho/Collision/RayCastOutput.cpp, PlayRho/Collision/RayCastOutput.hpp, PlayRho/Common/ArrayList.hpp, PlayRho/Common/BlockAllocator.cpp, PlayRho/Common/BlockAllocator.hpp, PlayRho/Common/Math.hpp, PlayRho/Common/Templates.hpp, UnitTests/DistanceJoint.cpp, UnitTests/TargetJoint.cpp, UnitTests/WeldJoint.cpp, UnitTests/WheelJoint.cpp, UnitTests/WorldJoint.cpp
Cleanups pre release 1.0.
Resolves issue #382.
=> Thanksgiving 2020

CMakeLists.txt, UnitTests/PrismaticJoint.cpp
Prevents me from being the Grinch? Holding back no more... here is release 1.0.
Documentation will be updated separately shortly after this.
=> Thanksgiving 2020 Release 1.0.0

Documentation/PhysicalUnits.md, PlayRho/Common/Units.hpp
Resolves issue #388 .
Minimal.
Issue #388: Update to native boost 1.75.0 for USE_BOOST_UNITS support.
=> Updates 20210309

PlayRho/Common/ArrayAllocator.hpp, PlayRho/Dynamics/BodyConf.hpp, PlayRho/Dynamics/WorldImpl.hpp, Testbed/Tests/RayCast.hpp, UnitTests/BodyConf.cpp
- Resolves issue #390: BodyConf doesn't support ==/!= operators
- Leverages size_type alias to shorten code.
- Updates Doxygen comments.
- Fixes out of bounds array access when firing bullets.
- Issue #390.
=> Updates 20210328

PlayRho/Common/Sweep.hpp, PlayRho/Dynamics/Body.cpp, PlayRho/Dynamics/Body.hpp, PlayRho/Dynamics/BodyConf.hpp, PlayRho/Dynamics/FixtureConf.hpp, UnitTests/Acceleration.cpp, UnitTests/Body.cpp, UnitTests/FixtureConf.cpp, UnitTests/Sweep.cpp
Provides more support for `==` & `!=` operators.
=> Updates 20210402

CMakeLists.txt
Rolls up recent changes from `v1.0.0` into a new release that's tagged `v1.1.0`.
=> Updates version

PlayRho/Common/Math.hpp
Generalizes Solve33 and Solve22
=> Generalizes Solve33 and Solve22

PlayRho/Dynamics/Body.hpp, PlayRho/Dynamics/WorldImpl.cpp
Minor tweaks:
- Updates function interface for `Body::SetInvMassData` to restrict inputs per intentions.
- Updates Doxygen documentation for `Body.hpp` respectively.
- Fixes a typo in a comment in `WorldImpl::SolveToiViaGS`.
=> Updates 20221221

.github/workflows/cmake.yml, UnitTests/CMakeLists.txt, UnitTests/World.cpp
Step towards using github CI instead of travis-ci.
=> Louis langholtz patch 1

PlayRho/Common/TypeInfo.hpp
Fixes some naming issues with custom type info support.
=> Fixes some naming issues with custom type info support

UnitTests/World.cpp, UnitTests/functional.cpp
Updates unit tests that were failing on Apple M2 Silicon
Issue #436.
=> Updates unit tests that were failing on Apple M2 Silicon

PlayRho/CMakeLists.txt, PlayRho/PlayRhoConfig.cmake.in, PlayRho/UsePlayRho.cmake
Improves cmake based project installation and re-use by other cmake projects.
- Issue #427
=> For issue 427 - cmake improvements

Benchmark/BenchmarkMain.cpp, Benchmark/CMakeLists.txt, CMakeLists.txt, appveyor.yml
Updates Benchmark to recent google benchmark
- Issue #444 .
=> Updates Benchmark to recent google benchmark

.github/workflows/docs.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, README.md, Testbed/CMakeLists.txt, UnitTests/Body.cpp, UnitTests/ChainShape.cpp, UnitTests/PolygonShape.cpp, UnitTests/World.cpp, UnitTests/WorldImpl.cpp, appveyor.yml, cmake/FindGLFW3.cmake
=> CI updates

.github/workflows/linux-debug.yml, Build/xcode5/PlayRho.xcodeproj/project.pbxproj, UnitTests/CheckedValue.cpp
Switches coveralls usage to its parallel model.
Hopefully limited to linux debug CI.
=> Switch coveralls to parallel model

Benchmark/CMakeLists.txt, HelloWorld/CMakeLists.txt, PlayRho/CMakeLists.txt, Testbed/CMakeLists.txt, UnitTests/CMakeLists.txt, UnitTests/World.cpp
Cherry picks commit 3fcca6e953c4b902060eeccf7543cdb947122499 into the release branch.
=> Fixes installed headers to being cmake configured ones

.github/workflows/linux-debug.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, Build/xcode5/PlayRho.xcodeproj/project.pbxproj, CMakeLists.txt, INSTALL.md, PlayRho/CMakeLists.txt, PlayRho/Common/TypeInfo.hpp, PlayRho/Dynamics/Joints/Joint.hpp, UnitTests/CMakeLists.txt, UnitTests/TypeInfo.cpp
At the moment, just tests building shared library on Windows and macOS.
=> Changes for exports/DLLs

Benchmark/CMakeLists.txt, HelloWorld/CMakeLists.txt, PlayRho/Common/TypeInfo.hpp, Testbed/CMakeLists.txt, UnitTests/CMakeLists.txt, UnitTests/World.cpp
More cleanups:
- Updates test expectations for Apple silicon w/ Real=double.
- More CMakeLists cleanups like more proper inclusion/linkage.
- Decreases need for RTTI to only non GCC/clang/MSVC compilers.
=> Updates 20230228

Benchmark/CMakeLists.txt, HelloWorld/CMakeLists.txt, PlayRho/Common/TypeInfo.hpp, Testbed/CMakeLists.txt, UnitTests/CMakeLists.txt, UnitTests/GearJoint.cpp, UnitTests/World.cpp
Brings changes from master branch to this branch. Specifically...
More cleanups:
- More CMakeLists cleanups like more proper inclusion/linkage.
- Decreases need for RTTI to only non GCC/clang/MSVC compilers.
- Updates test expectations for Apple silicon w/ Real=double.
=> Update release 20230228

.clang-tidy, .github/workflows/clang-tidy-review.yml
Adds a clang-tidy-review workflow & updates .clang-tidy file.
=> Adds a clang-tidy-review workflow & updates .clang-tidy file

PlayRho/Collision/Manifold.cpp, PlayRho/Collision/Manifold.hpp, PlayRho/Common/Math.hpp
Document/assert preconditions & turn off divide-by-zero linting.
=> Document/assert preconditions & turn off divide-by-zero linting

.clang-tidy, .github/workflows/codeql.yml, PlayRho/Collision/Manifold.hpp
=> Updates 20230303

.clang-tidy, PlayRho/Collision/Manifold.hpp, PlayRho/Collision/Shapes/MultiShapeConf.cpp, PlayRho/Collision/Shapes/PolygonShapeConf.cpp, PlayRho/Collision/Shapes/PolygonShapeConf.hpp, PlayRho/Collision/Shapes/Shape.hpp, PlayRho/Collision/SimplexEdge.hpp, PlayRho/Common/ArrayList.hpp, PlayRho/Common/BlockAllocator.cpp, PlayRho/Common/BlockAllocator.hpp, PlayRho/Common/GrowableStack.hpp, PlayRho/Common/IndexingNamedType.hpp, PlayRho/Common/Sweep.hpp, PlayRho/Common/Templates.hpp, PlayRho/Common/propagate_const.hpp, PlayRho/Dynamics/ContactImpulsesList.hpp, PlayRho/Dynamics/Contacts/ContactSolver.cpp, PlayRho/Dynamics/Contacts/PositionConstraint.hpp, PlayRho/Dynamics/Contacts/PositionSolverManifold.hpp, PlayRho/Dynamics/Joints/Joint.hpp, PlayRho/Dynamics/WorldImpl.cpp
Addresses a variety of `clang-tidy` related warnings and adds those back into the configuration for things to check.
=> Updates 20230309

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Common/DynamicMemory.cpp, PlayRho/Common/DynamicMemory.hpp, PlayRho/Common/Math.hpp, PlayRho/Common/StackAllocator.cpp, PlayRho/Common/StackAllocator.hpp, PlayRho/Common/VertexSet.hpp, UnitTests/Math.cpp
- Adds IsPowerOfTwo pure function to Math.hpp
- Fix benchmark application builds via XCode
- Minor updates to StackAllocator & VertexSet
- Unindents DynamicMemory code from its namespace & comments on use of header
=> Misc updates 20230721

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, PlayRho/Common/MemoryResource.cpp, PlayRho/Common/MemoryResource.hpp, PlayRho/Common/PoolMemoryResource.cpp, PlayRho/Common/PoolMemoryResource.hpp, PlayRho/Common/ThreadLocalAllocator.hpp, UnitTests/MemoryResource.cpp, UnitTests/PoolMemoryResource.cpp, UnitTests/ThreadLocalAllocator.cpp, UnitTests/polymorphic_allocator.cpp
=> Adds pmr interfaces

UnitTests/MemoryResource.cpp, UnitTests/PoolMemoryResource.cpp, UnitTests/ThreadLocalAllocator.cpp
Adds missing unit testing of new pmr code & fixes formatting.
=> Adds missing unit testing of new pmr code & fixes formatting

PlayRho/Dynamics/World.cpp, PlayRho/Dynamics/World.hpp, PlayRho/Dynamics/WorldContact.cpp, PlayRho/Dynamics/WorldContact.hpp, PlayRho/Dynamics/WorldImpl.cpp, PlayRho/Dynamics/WorldImpl.hpp, PlayRho/Dynamics/WorldImplMisc.cpp, PlayRho/Dynamics/WorldImplMisc.hpp, PlayRho/Dynamics/WorldSpecial.cpp, UnitTests/World.cpp
Increases `Worldimpl` & `World` flexibility.
=> Increases worldimpl world flexibility

PlayRho/Dynamics/WorldImpl.cpp, PlayRho/Dynamics/WorldImpl.hpp
- Refactors WorldImpl::m_bodyConstraints into bodyConstraints.
- Refactors WorldImpl::m_islanded* into WorldImpl::Islanded::*.
- More decoupling uses of Span in WorldImpl.
=> More worldimpl refactorings

PlayRho/Common/Positive.hpp, PlayRho/Dynamics/World.hpp, PlayRho/Dynamics/WorldConf.hpp, PlayRho/Dynamics/WorldImpl.cpp, PlayRho/Dynamics/WorldImpl.hpp, UnitTests/WorldConf.cpp
Makes more uses of polymorphic_allocator & makes more configurable.
=> Makes more uses of polymorphic_allocator & makes more configurable

PlayRho/Collision/Collision.cpp, PlayRho/Collision/Collision.hpp, PlayRho/Collision/Manifold.hpp, PlayRho/Collision/PointState.hpp, PlayRho/Collision/SeparationScenario.cpp, PlayRho/Collision/SeparationScenario.hpp, PlayRho/Collision/TimeOfImpact.cpp, PlayRho/Dynamics/Contacts/Contact.hpp, Testbed/Framework/Test.cpp, UnitTests/SeparationScenario.cpp, UnitTests/World.cpp
Various cleanups. See commit comments.
=> Updates 20230802

PlayRho/Common/Math.hpp, PlayRho/Common/StatsResource.hpp, UnitTests/PoolMemoryResource.cpp, UnitTests/StatsResource.cpp
Minor changes. See commit comments.
=> Updates 20230814

Library/include/playrho/d2/World.hpp, Library/include/playrho/d2/WorldImpl.hpp, Library/include/playrho/pmr/MemoryResource.hpp, Library/source/playrho/d2/WorldImpl.cpp, UnitTests/Compositor.cpp, UnitTests/ContactSolver.cpp, UnitTests/DistanceJoint.cpp, UnitTests/Math.cpp, UnitTests/World.cpp, UnitTests/WorldImpl.cpp
=> Updates 20230830

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, Library/CMakeLists.txt, Library/include/playrho/Finite.hpp, Library/include/playrho/Negative.hpp, Library/include/playrho/NonNegative.hpp, Library/include/playrho/NonPositive.hpp, Library/include/playrho/NonZero.hpp, Library/include/playrho/Positive.hpp, Library/include/playrho/UnitInterval.hpp, Library/include/playrho/d2/AabbTreeWorld.hpp, Library/include/playrho/d2/AabbTreeWorldBody.hpp, Library/include/playrho/d2/DynamicTree.hpp, Library/include/playrho/d2/World.hpp, Library/include/playrho/d2/WorldImpl.hpp, Library/include/playrho/detail/Checked.hpp, Library/include/playrho/detail/FiniteChecker.hpp, Library/include/playrho/detail/NegativeChecker.hpp, Library/include/playrho/detail/NonNegativeChecker.hpp, Library/include/playrho/detail/NonPositiveChecker.hpp, Library/include/playrho/detail/NonZeroChecker.hpp, Library/include/playrho/detail/PositiveChecker.hpp, Library/include/playrho/detail/UnitIntervalChecker.hpp, Library/source/playrho/d2/AabbTreeWorld.cpp, Library/source/playrho/d2/AabbTreeWorldBody.cpp, Library/source/playrho/d2/World.cpp, Testbed/Tests/iforce2d_TopdownCar.cpp, UnitTests/AabbTreeWorld.cpp, UnitTests/Checked.cpp
Primarily, bunch of Doxygen updates, and renames WorldImpl to AabbTreeWorld.
=> Updates 20230921

Library/include/playrho/Island.hpp, Library/include/playrho/d2/AabbTreeWorld.hpp, Library/include/playrho/d2/AabbTreeWorldBody.hpp, Library/include/playrho/d2/Body.hpp, Library/include/playrho/d2/DynamicTree.hpp, Library/include/playrho/detail/Checked.hpp, Library/include/playrho/detail/FiniteChecker.hpp, Library/include/playrho/detail/NegativeChecker.hpp, Library/include/playrho/detail/NonNegativeChecker.hpp, Library/include/playrho/detail/NonPositiveChecker.hpp, Library/include/playrho/detail/NonZeroChecker.hpp, Library/include/playrho/detail/PositiveChecker.hpp, Library/include/playrho/detail/UnitIntervalChecker.hpp, Library/source/playrho/d2/DynamicTree.cpp
Minor tweaks. See commit comments.
=> Updates 20230925

.github/workflows/docs.yml, Library/include/playrho/d2/Body.hpp
- Updates CI to generate docs for pushes to branches.
- Updates Doxygen docs for `Body` class.
=> Updates 20231001

Library/include/playrho/Contact.hpp, Library/include/playrho/Contactable.hpp, Library/source/playrho/d2/AABB.cpp, Library/source/playrho/d2/AabbTreeWorld.cpp, Library/source/playrho/d2/WorldManifold.cpp, UnitTests/AabbTreeWorld.cpp, UnitTests/Contact.cpp, UnitTests/Joint.cpp
Smaller batch of changes to increase unit test code coverage.
=> Updates 20231006

Benchmark/CMakeLists.txt, Changes.md, Testbed/CMakeLists.txt, UnitTests/CMakeLists.txt
- Updates application `CMakeLists.txt` files to support `FetchContent`.
- Updates `Changes.md` document to start documenting changes since release 1.1.
- Addresses Issue #530 .
=> Updates 20231007

INSTALL.md, UnitTests/CollideShapes.cpp, UnitTests/Manifold.cpp
- Updates `INSTALL.md`.
- Adds more unit test coverage of `GetManifold` code.
=> Updates 20231008

INSTALL.md, Library/source/playrho/d2/Manifold.cpp, UnitTests/CollideShapes.cpp
- Updates `INSTALL.md` more.
- Adds unit test coverage some yet covered paths of `GetManifold`.
- Reorders `GetManifold` processing to deal with more common cases before less common ones.
=> Updates 20231009

Build/xcode5/PlayRho.xcodeproj/project.pbxproj, INSTALL.md, Library/include/playrho/Contact.hpp, Library/include/playrho/IslandStats.hpp, Library/source/playrho/d2/AabbTreeWorld.cpp, Library/source/playrho/d2/World.cpp, README.md, UnitTests/Contact.cpp, UnitTests/IslandStats.cpp
=> Updates 20231010

INSTALL.md, Library/include/playrho/Contact.hpp, Library/include/playrho/d2/AabbTreeWorld.hpp, Library/include/playrho/d2/ChainShapeConf.hpp, Library/include/playrho/d2/UnitVec.hpp, Library/include/playrho/d2/World.hpp, Library/include/playrho/d2/WorldConf.hpp, Library/source/playrho/d2/AabbTreeWorld.cpp, Library/source/playrho/d2/TimeOfImpact.cpp, Library/source/playrho/pmr/StatsResource.cpp, README.md, UnitTests/AabbTreeWorld.cpp, UnitTests/World.cpp, UnitTests/WorldShape.cpp
- Updates `README.md` and `INSTALL.md`.
- Plumbs `GetResourceStats` through `World`.
- Updates some Doxygen docs.
- Updates unit testing to cover more code.
=> Updates 20231011

Changes.md, Library/CMakeLists.txt, Library/source/playrho/d2/MotorJointConf.cpp, UnitTests/MotorJoint.cpp
- CMake updates to improve external `Real` number type support.
- Updates `Changes.md` to mention these.
- Adds more unit test coverage of `MotorJointConf`.
- Finishes support for issue #295.
=> Updates 20231024

Library/include/playrho/Contact.hpp, Library/include/playrho/Doxygen.hpp, Library/include/playrho/ObjectPool.hpp, Library/include/playrho/d2/AABB.hpp, Library/include/playrho/d2/AabbTreeWorld.hpp, Library/include/playrho/d2/Body.hpp, Library/include/playrho/d2/DistanceJointConf.hpp, Library/include/playrho/d2/EdgeShapeConf.hpp, Library/include/playrho/d2/FrictionJointConf.hpp, Library/include/playrho/d2/GearJointConf.hpp, Library/include/playrho/d2/MotorJointConf.hpp, Library/include/playrho/d2/NgonWithFwdNormals.hpp, Library/include/playrho/d2/PrismaticJointConf.hpp, Library/include/playrho/d2/PulleyJointConf.hpp, Library/include/playrho/d2/RevoluteJointConf.hpp, Library/include/playrho/d2/WeldJointConf.hpp, Library/include/playrho/d2/WheelJointConf.hpp, Library/include/playrho/d2/World.hpp, Library/include/playrho/d2/WorldBody.hpp, Library/include/playrho/d2/WorldContact.hpp, Library/include/playrho/d2/WorldShape.hpp, Library/include/playrho/d2/detail/WorldConcept.hpp, Library/include/playrho/d2/detail/WorldModel.hpp, Library/source/playrho/d2/AabbTreeWorld.cpp, Library/source/playrho/d2/WorldBody.cpp, UnitTests/AabbTreeWorld.cpp, UnitTests/Contact.cpp, UnitTests/World.cpp
Mostly Doxygen doc improvements. But also makes `World` equality comparable and some small cleanups.
=> Updates 20231030

Library/include/playrho/ContactFeature.hpp, Library/include/playrho/d2/Manifold.hpp, Library/source/playrho/d2/AabbTreeWorld.cpp, Library/source/playrho/d2/Manifold.cpp, Library/source/playrho/d2/WorldManifold.cpp, UnitTests/AabbTreeWorld.cpp, UnitTests/ContactFeature.cpp, UnitTests/PositionConstraint.cpp, UnitTests/World.cpp
Basically, cleans up code related to `Manifold`.
- Closes #569.
=> Updates 20240109
